apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: sre-demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: us-east-1
