apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo-app
  labels:
    app: sre-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-demo-app
  template:
    metadata:
      labels:
        app: sre-demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: app
          image: sre-demo-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: REGION
              value: REPLACE_REGION
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
